### ISSUE TITLE
HUNGARIAN dictionary is crashing the tool

### ISSUE THREAD

**Issue by JeanClaudeCottier** [streetsidesoftware/hunspell-reader#3]
I can't convert any Hungarian dictionaries. I'm building a word game and I need to get list of all the words possible. Your tools has been a gold mine for me, thank you very much (I converted many languages into list of words). Sadly, it doesn't work for Hungarian, can you have a look please. Thanks.

![hungarian](https://user-images.githubusercontent.com/19557896/63690346-af6f9900-c80c-11e9-9560-a2b8345521b9.png)

**Comment by Jason3S** [comment]
I'll take a look when I get the chance. I'm not sure if it will be able to compile Hungarian due to the size of the resulting word list.

**Comment by Jason3S** [comment]
With #5 it is now possible to limit the depth in which suffixes are applied. It is a step in the right direction.

**Comment by Jason3S** [comment]
I have fixed the crashing issue and added the ability the limit the depth. Hungarian will still generate millions of words.

**Comment by Jason3S** [comment]
@JeanClaudeCottier it should work for you now.
Watch out for the version of the Hungarian dictionary you are using. Many of them seem to have encoding issues.

You might need to limit the depth, otherwise you will get too many words.
Use `-m 0` or `-m 1`:
```
hunspell-reader words -m 0 dictionaries/hu/hu.dic
```

**Comment by JeanClaudeCottier** [comment]
Thanks a lot it works. It is generating almost 75M words... Now, it's going to take a while to process :)
